-*- mode: org; fill-column: 95 -*-
@title About

Я Rigidus, а это мой хомяк. Хомяк — страшная сила. Раньше, когда этот
хомяк был белым и хостился на мастерхосте и был написан, страшно
сказать, на php, я сослался с него на свой старый блог. Это была
роковая ошибка.

Капча не помогла, пришлось все заморозить и отключить нахрен все
комментарии. Ибо нефиг. Сначала они вставили рекламу — я терпел. Потом
придумали свои "кирилические сервисы" — я терпел. Но пара десятков
комментариев с порнухой в день — это извините перебор.

* Happy new Year (2011)

И тут случился новый год. А новый год - это, знаете ли такое время,
когда настоящий программист одинок, грустит и сидит за
компьютером. Так что я как минимум на ⅓ настоящий программист.

И тут я подумал: «Доколе!». Почему в то время, как я на работе пишу на
лучшем из языков программирования мой хомяк написан, стыдно сказать на
чем! Коллеги не поймут! В общем, было принято решение все
менять. <s>Флаг, герб и гимн.</s> Так мой хомяк стал черным, злым и
приготовился противостоять хабраэффекту. Вот и посмотрим..

* Работа

Я работаю в компании, которая платит мне за то, что я пишу веб-решения
на Common Lisp. Да, я получаю от этого не только деньги, но и
удовольствие. Я люблю свою работу.

Раньше я работал в другой компании и был ведущим разработчиком на
php. Это в половину не было так круто как сейчас, но я тоже любил свою
работу.

Вообще, любовь к работе - это моя патологическая черта..
